import = ["~/.config/alacritty/catppuccin-mocha.toml"]
[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["--login", "--interactive", "-c", "tmux new -A"]

[window]
decorations = "none"
padding = { x = 7, y = 0 }
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[font]
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[selection]
save_to_clipboard = false

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Q", mods = "Control", action = "Quit" },
]
